**Problem 1**

Import Numpy as np

In [1]:
import numpy as np


**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [38]:
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array1)

[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [44]:
all_true_array = np.array([[True, True, True], [True, True, True], [True, True, True]])
print(all_true_array)

arr = [True] * 3
arr = [arr] * 3
print(arr)

array2= np.ones((3,3), dtype=bool)
print(array2)

array_true=np.full([3,3],True)
print(array_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[True, True, True], [True, True, True], [True, True, True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [45]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1::2])

mask = arr%2 != 0
b = arr[mask]
print(b)

[1 3 5 7 9]
[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2] = -1
print(arr[1::2])

arr[arr %2 == 1] = -1
print(arr)

[-1 -1 -1 -1 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [13]:
print(np.arange(10).reshape(2,5))


[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [24]:
a = np.arange(10).reshape(5,-1)
b = np.repeat(1, 10).reshape(5,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


**Problem 8**

Stack the arrays a and b horizontally.

In [27]:
print(a.reshape(-1, 10))
print(b.reshape(-1, 10))

[[0 1 2 3 4 5 6 7 8 9]]
[[1 1 1 1 1 1 1 1 1 1]]


**Problem 9**

Get the common items between a and b.

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]
[[1 2 3 2 3 4 3 4 5 6]]


**Problem 10**

From array a remove all items present in array b

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a, b)
print(a)

[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [86]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = a[a<10]
print(b[5<b])
print(a[np.logical_and(a>5 , a<10)])

[6 9]
[6 9]


**Problem 13**

Swap columns 1 and 2 in the array arr.

In [66]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [0,1]] = arr[:, [1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [72]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [95]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.flip(arr, 0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 16**

Reverse the columns of a 2D array arr.

In [97]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.flip(arr, 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [111]:
#import random
#print(np.full((5,3),random.randrange(5,10)))
#print(np.random.uniform(5,10,[5,3]))
print((np.random.rand(5,3) * 5) + 5)

[[5.759 8.876 9.202]
 [8.875 8.883 9.707]
 [6.255 5.303 8.368]
 [7.08  6.12  7.54 ]
 [9.666 6.949 6.401]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [116]:
rand_arr = np.array([1.123456, 2.456756, 55.7759994])
np.set_printoptions(precision=3)
print(rand_arr)
another_arr = (np.random.rand(5,3) * 5) + 5
print(np.round(another_arr, 3))


[ 1.123  2.457 55.776]
[[9.357 8.682 9.839]
 [8.99  9.444 9.38 ]
 [9.315 5.588 6.342]
 [8.507 6.015 6.242]
 [6.23  9.031 9.211]]
